### ISSUE TITLE
clean up parameter management

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/jesd204b#10]
If there is really a need for splitting between "physical" and "transport" sets of parameters, then the retrieval of parameters should not be done by bruteforcing into each set of parameters, and ignoring errors by silently setting fields that aren't found anywhere to 0.

**Comment by sbourdeauducq** [comment]
FWIW the Rust code that does some of that looks like this:
https://github.com/m-labs/artiq/blob/c2d86c4f67d289ae38463fda8127e6d969f7d8ff/artiq/firmware/libboard/ad9154.rs#L74

**Comment by enjoy-digital** [comment]
thanks, I'll look at the Rust code and will fix that.

**Comment by enjoy-digital** [comment]
Done via https://github.com/m-labs/jesd204b/commit/2d4374f28fce62b020997bd7b80777790f0a08b4.
