### ISSUE TITLE
use elastic buffers instead of async FIFO

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/jesd204b#2]
https://github.com/enjoy-digital/litejesd204b/commit/2011a5f243d1b187420d17f5cceb8893790c5b16#commitcomment-19089435

**Comment by enjoy-digital** [comment]
done: https://github.com/m-labs/jesd204b/commit/1a88bf9f43764ae537471938f5d19e5c19e2bc2a

**Comment by enjoy-digital** [comment]
- add AsyncResetSynchronizer inside module
- use fixed initial_delay = depth/2
- move to migen/cdc

**Comment by enjoy-digital** [comment]
done via:
https://github.com/m-labs/jesd204b/commit/1a22d6b3f01b0cbebd9965b48cfabe054a321133
https://github.com/m-labs/migen/commit/15c0d1c0dbdab171b789edb4549b6f31ef4110a5
and tested onboard at 10gbps.

You can close this if that's fine for you.
