### ISSUE TITLE
ditch the elastic buffers

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/jesd204b#8]
The procedure "Using TX Buffer Bypass in Multi-Lane Manual Mode" in the GTX user guide should make them unnecessary.

**Comment by jordens** [comment]
Do you know whether that meets timing?

**Comment by sbourdeauducq** [comment]
I don't know, but we can add pipeline registers if it doesn't.

**Comment by jordens** [comment]
That wouldn't help if it fails timing due to jitter or skew/delay/phase uncertainty between the clocks.

**Comment by sbourdeauducq** [comment]
My understanding of the Xilinx transceiver guide is the slave lanes adjust their internal clocks to align with TXUSRCLK. TXUSRCLK is provided to each transceiver by a BUFG network so this should not be a problem.

**Comment by jordens** [comment]
Ok. But that's quite a bit more than just ditching the EBs.

**Comment by sbourdeauducq** [comment]
Yes, the procedure I mentioned must be followed. We'll need that procedure for DRTIO as well. And most of it is required for porting to GTH since they don't have a fully automatic TX phase alignment circuit.

**Comment by enjoy-digital** [comment]
This does not seem coherent with the approach you have of the transceivers: only considering them as simple serializers/deserializers. You are going to use a specific feature of the transceivers for that but then why are we using a 8b/10b encoder in  the fabric and not the one provided by the transceiver? Is it to avoid too much clock domains and reduce buffer usage? Or simply to have only one clock domain for the core?

**Comment by enjoy-digital** [comment]
Also this can prevent using the core on non-Xilinx FPGAs (I don't know if this feature is available on Altera/Lattice FPGAs)

**Comment by sbourdeauducq** [comment]
Asking a simple serializer to use the parallel clock you give it isn't a tall order; even the Spartan-6 IOSERDES support that. And yes, this is for reducing the number of clock domains, and in the case of DRTIO have fixed latencies.

For JESD204 on non-Xilinx FPGAs, one can fall back to elastic buffers if required.

**Comment by sbourdeauducq** [comment]
Not done nor desirable as the elastic buffers are actually useful to deal with Xilinx clocking snafu.
