### ISSUE TITLE
always react to SYNC requests

### ISSUE THREAD

**Issue by jordens** [m-labs/jesd204b#9]
redo `link.start` so that the core/the link re-enter CGS/ILAS when synchronization is lost (not just the first time after `enable`)

**Comment by sbourdeauducq** [comment]
Right now the SYNC signal status is reported outside the JESD core and with a ARTIQ TTL, which is overkill and inappropriate. It would be better to let the JESD core report if a resync has occured (since the last CSR reset) via a CSR that can be reset by the CPU.

**Comment by jordens** [comment]
That's not my issue here. Right now SYNC drives `core.start`. It's just that the behavior should be self-healing and not single-shot. Then the CPU can monitor if it wants.

**Comment by sbourdeauducq** [comment]
I know, but this addition of the CPU monitoring register in the JESD core is certainly best done with this in a single shot.

**Comment by enjoy-digital** [comment]
The core is now reacting to SYNC requests. The report part is still missing, going to add it before closing.

**Comment by enjoy-digital** [comment]
We are now able to monitor restarts via https://github.com/m-labs/jesd204b/commit/4af8d970729c991e4f98d122a8a521de6d65495d.
